server:
  port: 8001

spring:
  application:
    name: provider8001
  datasource:
    url: jdbc:mysql://localhost:3306/mircroservicereview?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: rootAdmin

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: org.person.pojo

#Eureka服务注册中心也会将自己作为客户端来尝试注册它自己，所以我们需要禁用它的客户端注册行为。
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://localhost:7001/eureka

  # 配置Swagger相关信息
instance:
  prefer-ip-address: true
  instanceId: ${spring.cloud.client.ipAddress}:${server.port}
  status-page-url: http://${spring.cloud.client.ipAddress}:${server.port}/swagger-ui.html
    # ${server.port}为该服务的端口号